---
title: "grafic_emocional"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(fmsb)
set.seed(99)
```

```{r}
# Create data: note in High school for several students

data=as.data.frame(matrix( sample(0:20, 8 , replace=F) , ncol=4))
data=as.data.frame(matrix( sample(4, 8, replace=T) , ncol=4))
colnames(data)=c("Social" , "Familiar" , "Escolar" , "Personal")
rownames(data)=c("Lleu" , "Greu")
 
# To use the fmsb package, I have to add 2 lines to the dataframe: the max and min of each topic to show on the plot!
data=rbind(rep(4,4) , rep(0,4) , data)
 
groc = col2rgb("yellow2")
groc_bo = rgb(groc[1],groc[2],groc[3],alpha = 120, maxColorValue = 255)
vermell = col2rgb("red2",alpha = 0.5)
vermell_bo = rgb(vermell[1],vermell[2],vermell[3],alpha = 120, maxColorValue = 255)

#==================
# Plot 1: Default radar chart proposed by the library:
radarchart(data, 
           pcol = c(vermell_bo, groc_bo),
           pfcol= c(vermell_bo, groc_bo),
           plty = c(1,1),
           title="Riscs emocionals")
legend(x = "topright", legend = c("Risc lleu", "Risc greu"), col = c(groc_bo, vermell_bo), seg.len = 1, border = "transparent", pch = 16, lty = 1, cex = 0.75)

```

Barplot:

```{r}
library(reshape2)
library(ggplot2)
dat = data[3:4,]

crp = colorRamp("yellow3", "red3", 30)
dat$color = c("yellow3", "red3")
dat2 <- melt(dat, id.vars = "color")

ggplot(dat2, aes(x=variable, y=value)) + 
  geom_bar(stat="identity", fill=dat2$color) +
  xlab("\nÀmbit") +
  ylab("Risc\n") +
  guides(fill=FALSE) +
  labs(title = "Riscs emocionals i socials") +
  coord_flip() +
  theme_bw()

dades = c(4,3,2,1,3)
valors = c(4-dades[1], 4-dades[2], 4-dades[3], min(4,(4-dades[4] + 4 - dades[5])))
arees = c("Personal", "Escolar", "Social", "Familiar")

df_emocional = as.data.frame(cbind(arees, valors))

nom = "Pepet Pepito"
ggplot(df_emocional, aes(x = factor(arees, levels = arees[c(4,3,2,1)]), 
                         y = as.numeric(as.character(valors)))) + 
  geom_bar(stat="identity", aes(fill = as.numeric(as.character(df_emocional$valors)))) + 
  scale_fill_gradientn(colours = rev(heat.colors(4))) + 
  theme_bw() +
  theme(legend.position="none", 
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  coord_flip() +
  ylab("") +
  ylim(c(0,4)) +
  xlab("Àrees") +
  labs(title = "Riscs emocionals")
 
```

```{r}
dades = c(4,3,2,1,4,3,2,1,1,4,1,4,2,3,1,1)
pre_valors = c(max(3-dades[1],0),        # m'agrada com sóc
           max(dades[2]-2,0),        # estic trist
           max(2-dades[3],0),        # crec que sé fer moltes coses
           max(dades[4]-2,0),        # m'enfado i em barallo
           min(max(3-dades[5],0),1), # m'agrada anar a l'escola
           min(max(dades[6]-2,0),1), # m'avorreixo a classe
           max(2-dades[7],0),        # trec bones notes
           max(2-dades[8],0),        # estudio i m'esforço
           max(3-dades[9],0),        # em cauen bé els meus companys
           max(dades[10]-2,0),       # els altres em molesten
           max(3-dades[11],0),       # m'agrada jugar amb els altres
           max(dades[12]-2,0),       # em costa fer amics
           max(3-dades[13],0),       # estic a gust a casa
           max(dades[14]-2,0),       # hi ha crits i discussions a casa
           min(max(3-dades[15],0),1), # estic d'acord amb les normes de casa
           min(max(4-dades[16],0),2)  # estimo els meus pares
           )

valors = c()

for (i in 1:4){
  valors[i] = sum(pre_valors[((i-1)*4):(i*4)])
}

arees = c("Personal", "Escolar", "Social", "Familiar")

df_emocional = as.data.frame(cbind(arees, valors_arees))

nom = "Pepet Pepito"
ggplot(df_emocional, aes(x = factor(arees, levels = arees[c(4,3,2,1)]), 
                         y = as.numeric(as.character(valors)))) + 
  geom_bar(stat="identity", aes(fill = as.numeric(as.character(df_emocional$valors)))) + 
  scale_fill_gradientn(colours = rev(heat.colors(9))) + 
  theme_bw() +
  theme(legend.position="none", 
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  coord_flip() +
  ylab("") +
  xlab("Àrees") +
  labs(title = "Riscs emocionals")
```